module.exports = {
  comparisonCities: [
    { city: "Ljubljana", country: "Slovenia" },
    { city: "Prague", country: "Czech Republic" },
    { city: "Bratislava", country: "Slovakia" },
    { city: "Warsaw", country: "Poland" },
    { city: "Budapest", country: "Hungary" },
    { city: "Tallinn", country: "Estonia" },
    { city: "Belgrade", country: "Serbia" },
    { city: "Zagreb", country: "Croatia" },
    { city: "Riga", country: "Latvia" },
    { city: "Vilnius", country: "Lithuania" },
    { city: "Bucharest", country: "Romania" },
    { city: "Athens", country: "Greece" },
    { city: "Lisbon", country: "Portugal" },
    { city: "Vienna", country: "Austria" },
    { city: "Rome", country: "Italy" },
    { city: "Madrid", country: "Spain" },
    { city: "Berlin", country: "Germany" },
    { city: "Paris", country: "France" },
    { city: "London", country: "United Kingdom" },
    { city: "Oslo", country: "Norway" },
    { city: "Copenhagen", country: "Denmark" },
  ],
  baseCity: { city: "Sofia", country: "Bulgaria" },
};
